export const GET_SUBREDDITS='GET_SUBREDDITS';
export const GET_SUBREDDITS_START='GET_SUBREDDITS_START';
export const GET_SUBREDDITS_SUCCESS='GET_SUBREDDITS_SUCCESS';
export const GET_SUBREDDITS_FAILURE='GET_SUBREDDITS_FAILURE';





