export const GET_SUBREDDITS='GET_SUBREDDITS';
export const GET_SUBREDDITS_START='GET_SUBREDDITS_START';
export const GET_SUBREDDITS_SUCCESS='GET_SUBREDDITS_SUCCESS';
export const GET_SUBREDDITS_FAILURE='GET_SUBREDDITS_FAILURE';


export const MAKE_FAVORITE='MAKE_FAVORITE';
export const REMOVE_FAVORITE='REMOVE_FAVORITE';


export const GET_FROM_CACHE='GET_FROM_CACHE';




